# -*- coding: utf-8 -*-
"""

Created on 24/11/2024

@author: Sully Mak, Guillaume Cantin, Benoît Delahaye
Nantes Université - LS2N 

This script contains function to read the solution file generated by FreeFem++ and clean output folders.
"""
import numpy as np
import pandas as pd

from scipy.interpolate import griddata
import os, shutil

def solution(filename):
    '''
    Parameters
    ----------
    filename : STR
        Name of the file that contains solutions.

    Returns
    -------
    DF : list of Dataframe that contains solution at indice corresponding to times
    times : list of values of the discretised time

    '''    

    data = []
    T = []
    with open(filename, 'r') as f:
        # Ignorer la première ligne (en-tête)
        header = f.readline()
    
        # Lire les données ligne par ligne
        for line in f:
            t, x, y, u1, w1, u2, w2 = map(float, line.split())  # Convertir chaque élément en float


            data.append((t, x, y, u1, w1, u2, w2))  # Ajouter (x, y, u) pour le temps t
    
    data = np.array(data)
    times = np.unique(data[:, 0])
    DF = [pd.DataFrame(data[data[:, 0] == t][:,1:], 
                                      columns=["x", "y", "u1", "w1", "u2", "w2"]) for t in times]

    

    return DF, times

def clean(folder = 'output/heatmaps'):
    
    for filename in os.listdir(folder):
        file_path = os.path.join(folder, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (file_path, e))
# Fonction pour plot les données du fichier FreeFem++

